name: Deploy Environment

on:
  workflow_dispatch:
    inputs:
      OS:
        description:
        type: choice
        options:
          - ubuntu2204
          - ubuntu_python
          - win11
      action:
        description:
        type: choice
        options:
          - plan
          - apply
          - destroy
      expiry:
        description: auto-destroy in days?
        type: choice
        options:
          - 1
          - 2
          - 3
          - 4 
          - 5

env:
 ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
 ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
 ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
 ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
 TF_VAR_ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
 TF_VAR_ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
 TF_VAR_ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
 TF_VAR_ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}


jobs:
  check:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    if: github.event.inputs.action == 'plan' 
    name:  check
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16        

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
          
      - name: Terraform Init
        id: init
        run: |
          cd os/${{ github.event.inputs.OS }}/
          terraform init -no-color -input=false 
  
      - name: Terraform plan
        id: Plan
        run: |
          cd os/${{ github.event.inputs.OS }}
          terraform plan -no-color -input=false 
        continue-on-error: false


  destroy:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    if: github.event.inputs.action == 'destroy' 
    name:  destroy
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16        

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
          
      - name: Terraform Init
        id: init
        run: |
          cd os/${{ github.event.inputs.OS }}/
          terraform init -no-color -input=false 
  
      - name: Terraform destroy
        id: destroy
        run: |
          cd os/${{ github.event.inputs.OS }}/
          terraform destroy -auto-approve -no-color -input=false
        continue-on-error: false
        
  apply:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    if: github.event.inputs.action == 'destroy' 

    name:  Apply
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16        

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
          
      - name: Terraform Init
        id: init
        run: |
          cd os/${{ github.event.inputs.OS }}
          terraform init -no-color -input=false 
        continue-on-error: false

     
      - name: Terraform plan
        id: Plan
        run: |
          cd os/${{ github.event.inputs.OS }}
          terraform plan -no-color -input=false -var expiry=${{ github.event.inputs.expiry }} -out=plan
        continue-on-error: false

             
      - uses: actions/upload-artifact@v3
        with:
          name: plan
          path: os/${{ github.event.inputs.OS }}/plan
        continue-on-error: true

      - name: Terraform Apply
        id: Apply
        run: |
          cd os/${{ github.event.inputs.OS }}
          terraform apply -auto-approve -no-color -input=false -var expiry=${{ github.event.inputs.expiry }}
        continue-on-error: false
        