name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      OS:
        description:
        type: choice
        options:
          - win11
          - ubuntu


env:
 ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
 ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
 ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
 ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
 TF_VAR_ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
 TF_VAR_ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
 TF_VAR_ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
 TF_VAR_ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}


jobs:
  ubuntu:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name:  Apply
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16        

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
          
      - name: Terraform Init
        id: init
        run: |
          cd ${{ github.event.inputs.OS }}
          terraform init -no-color -input=false 

      - name: Terraform Apply
        id: Apply
        run: |
          cd ubuntu
          terraform apply -auto-approve -no-color -input=false
        continue-on-error: false
        