name: Periodic Expired Resources Un-Deploy

on:
  schedule:
    - cron: '00,30 * * * *'

env:
 ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
 ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
 ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
 ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
  undeploy:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name:  expired
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
          
      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
  
      - name: Terraform expired
        id: expired
        run: |
          ./scripts/expired.sh 2>&1 >> ./expired.log
          cd os/$(cat ./expired.log)
          terraform init
          terraform destroy -auto-approve
        continue-on-error: false

      - uses: actions/upload-artifact@v3
        with:
          name: expired
          path: expired.log