name: Test

on:
  push:
    branches: 
      - 'pr_*'  
      - 'main'
  workflow_dispatch:
    inputs:
      action:
  # checkov:skip=BC_REPO_GITHUB_ACTION_7: ADD REASON
        description: Choose Action 
        type: choice
        options:
          - plan
          - apply
          - destroy
      OS:
        description: Choose Environment
        type: choice
        options:
          - ubuntu2204
          - ubuntu2204python
          - win10
          - win11
      expiry:
        description: Auto-expire new resources in days
        type: choice
        options:
          - 0
          - 1
          - 2
          - 3
          - 4 
          - 5

env:
 ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
 ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
 ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
 ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}


jobs:
  common:
    runs-on: ubuntu-latest 
    name:  common
    steps:
      - name: show
        id: show
        run: |
          echo '${{ github.event_name }}' >> $GITHUB_STEP_SUMMARY
          echo '${{ github.ref_name }}' >> $GITHUB_STEP_SUMMARY

  plan:
    runs-on: ubuntu-latest 
    if: contains('twst', ${{ github.ref_name }} )
    name:  plan
    needs: common
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v3
   
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
          
      - name: Terraform Init
        id: init
        run: |
          echo 'plan' >> $GITHUB_STEP_SUMMARY
          ls -l > file.txt
      - uses: actions/upload-artifact@v2
        with:
          name: file
          path: file.txt
        
  apply:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    if: github.ref_name == 'main' 
    name:  Apply
    needs: plan
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v3  
        
      - uses: actions/download-artifact@v2
        with:
          name: file
          path: ./test.txt
          
      - name: Terraform Apply
        id: Apply
        run: |
          cat test.txt >> $GITHUB_STEP_SUMMARY

        
